<?php
/**
 * FILE PURPOSE: Public sports/court information page.
 * DEBUGGING: Presentation page; reservation CTAs route through the shared reservation notice flow.
 */
$pageTitle = 'Sports Court';
include __DIR__ . '/includes/header.php';
$rates = reservation_pricing_config();
?>
<section class="page-hero"><div class="container"><span class="eyebrow">Sports Court</span><h1>Train, play, and compete</h1><p>Reserve the shared multipurpose court for basketball or volleyball practices, games, clinics, leagues, and tournaments.</p></div></section>
<section class="section"><div class="container grid-2"><article class="card feature-card"><div class="icon-box">🏀</div><h2>Basketball</h2><p class="muted">Ideal for team practice, private training, friendly matches, leagues, and organized tournaments.</p><div class="rate-card"><span>Regular introductory rate</span><strong><?= money($rates['intro_fan_rate']) ?> fan · <?= money($rates['intro_aircon_rate']) ?> aircon</strong></div><div class="rate-card"><span>Tournament rate, 30–200 guests</span><strong><?= money($rates['tournament_fan_rate']) ?> fan · <?= money($rates['tournament_aircon_rate']) ?> aircon</strong></div><a class="btn btn-primary btn-block" style="margin-top:22px" href="reserve.php?type=basketball">Reserve Basketball</a></article><article class="card feature-card"><div class="icon-box">🏐</div><h2>Volleyball</h2><p class="muted">Suitable for training, scrimmages, clinics, friendly matches, and formal volleyball competitions.</p><div class="rate-card"><span>Regular introductory rate</span><strong><?= money($rates['intro_fan_rate']) ?> fan · <?= money($rates['intro_aircon_rate']) ?> aircon</strong></div><div class="rate-card"><span>Tournament rate, 30–200 guests</span><strong><?= money($rates['tournament_fan_rate']) ?> fan · <?= money($rates['tournament_aircon_rate']) ?> aircon</strong></div><a class="btn btn-primary btn-block" style="margin-top:22px" href="reserve.php?type=volleyball">Reserve Volleyball</a></article></div><div class="container" style="margin-top:24px"><p class="small muted">Introductory regular rates apply August 1–October 31, 2026. Original regular rates begin November 1, 2026. All bookings use complete whole hours.</p></div></section>
<section class="section surface"><div class="container split"><div class="visual-panel"></div><div><span class="eyebrow">Important Scheduling Rule</span><h2>The court is a shared venue</h2><p class="muted">Basketball, volleyball, and event reservations all use the same master calendar. Once a time is held by an active reservation, it is unavailable for every other reservation type.</p><div class="check-list"><div class="check-item"><b>✓</b><span>Whole-hour start and end times</span></div><div class="check-item"><b>✓</b><span>No overlapping active reservations</span></div><div class="check-item"><b>✓</b><span>Admin confirmation before final approval</span></div></div><a class="btn btn-dark" href="availability.php">View Reservation Calendar</a></div></div></section>
<?php include __DIR__ . '/includes/footer.php'; ?>
