<?php
/**
 * FILE PURPOSE: Public reservation terms and policy page.
 * DEBUGGING: Keep policy wording synchronized with the actual cancellation/payment rules implemented in code.
 */
 $pageTitle='Reservation Policies'; include __DIR__ . '/includes/header.php'; ?>
<section class="page-hero"><div class="container"><span class="eyebrow">Venue Policies</span><h1>Reservation guidelines</h1><p>These general guidelines may be updated by venue administration and supplemented by your approved reservation agreement.</p></div></section>
<section class="section"><div class="container grid-2"><div class="card"><h3>Reservation Approval</h3><p class="muted">An online submission is a reservation request only and does not hold or secure the selected schedule. The time slot becomes reserved only after admin approval. If another reservation is approved first, the request may need to be rejected or moved.</p></div><div class="card"><h3>Shared Venue Calendar</h3><p class="muted">Basketball, volleyball, and event bookings use one multipurpose venue. Approved reservations and staff-entered bookings block the shared schedule. Pending website requests remain visible to staff but do not block availability.</p></div><div class="card"><h3>Setup and Cleanup</h3><p class="muted">Approved event setup and cleanup time becomes part of the reserved schedule. Clients should not enter before the confirmed access time.</p></div><div class="card"><h3>Payments and Deposits</h3><p class="muted">A deposit may be required to maintain approval. Final pricing and payment deadlines will be provided by venue administration.</p></div><div class="card"><h3>Changes and Cancellations</h3><p class="muted">Schedule changes remain subject to availability. When a client cancels an active reservation, 50% of the reservation price is retained as the cancellation charge. Any verified amount paid above that charge is refundable; when the amount paid is below the charge, the difference remains due. Refunds are completed through the payment method or arrangement confirmed by venue administration.</p></div><div class="card"><h3>Venue Responsibility</h3><p class="muted">Clients are responsible for guests, equipment, damages, cleanliness, and compliance with safety and venue rules during the reservation.</p></div></div></section>
<?php include __DIR__ . '/includes/footer.php'; ?>
