CREATE TABLE IF NOT EXISTS rental_cancellations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  rental_id BIGINT UNSIGNED NOT NULL,
  original_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  paid_before_cancellation DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  refund_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  retained_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  security_deposit_held DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  refund_method VARCHAR(80) NULL,
  refund_reference VARCHAR(120) NULL,
  refund_notes TEXT NULL,
  refund_payment_id BIGINT UNSIGNED NULL,
  cancellation_reason VARCHAR(1000) NOT NULL,
  cancelled_by INT UNSIGNED NULL,
  cancelled_at DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_rental_cancellation_rental (rental_id),
  KEY idx_rental_cancellation_date (cancelled_at),
  KEY idx_rental_cancellation_admin (cancelled_by),
  KEY idx_rental_cancellation_refund_payment (refund_payment_id),
  CONSTRAINT fk_rental_cancellation_rental FOREIGN KEY (rental_id) REFERENCES rentals(id) ON DELETE CASCADE,
  CONSTRAINT fk_rental_cancellation_admin FOREIGN KEY (cancelled_by) REFERENCES admins(id) ON DELETE SET NULL,
  CONSTRAINT fk_rental_cancellation_refund_payment FOREIGN KEY (refund_payment_id) REFERENCES rental_payments(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
