-- TLH v1.3.0 - Generic Rentals Engine
-- Existing Food Stall data is preserved and migrated into the new generic tables.

CREATE TABLE IF NOT EXISTS rental_categories (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  slug VARCHAR(120) NOT NULL,
  category_type ENUM('space','equipment','other') NOT NULL DEFAULT 'space',
  default_availability_mode ENUM('exclusive','quantity') NOT NULL DEFAULT 'exclusive',
  default_billing_mode ENUM('one_time','monthly') NOT NULL DEFAULT 'one_time',
  allow_flexible_dates TINYINT(1) NOT NULL DEFAULT 1,
  allow_utilities TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_rental_category_name (name),
  UNIQUE KEY uq_rental_category_slug (slug),
  KEY idx_rental_category_active (is_active,sort_order),
  CONSTRAINT fk_rental_category_admin FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rentables (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  category_id INT UNSIGNED NOT NULL,
  code VARCHAR(60) NOT NULL,
  name VARCHAR(160) NOT NULL,
  location VARCHAR(160) NULL,
  availability_mode ENUM('exclusive','quantity') NOT NULL DEFAULT 'exclusive',
  total_quantity INT UNSIGNED NOT NULL DEFAULT 1,
  billing_mode ENUM('one_time','monthly') NOT NULL DEFAULT 'one_time',
  allow_flexible_dates TINYINT(1) NOT NULL DEFAULT 1,
  allow_utilities TINYINT(1) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  legacy_food_stall_id INT UNSIGNED NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_rentable_code (code),
  UNIQUE KEY uq_rentable_legacy_food_stall (legacy_food_stall_id),
  KEY idx_rentable_category (category_id,is_active),
  KEY idx_rentable_active (is_active,code),
  CONSTRAINT fk_rentable_category FOREIGN KEY (category_id) REFERENCES rental_categories(id) ON DELETE RESTRICT,
  CONSTRAINT fk_rentable_admin FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rentals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  reference_no VARCHAR(40) NOT NULL,
  client_name VARCHAR(160) NOT NULL,
  contact_number VARCHAR(50) NULL,
  organization VARCHAR(160) NULL,
  schedule_type ENUM('continuous','flexible') NOT NULL DEFAULT 'continuous',
  billing_mode ENUM('one_time','monthly') NOT NULL DEFAULT 'one_time',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  base_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  amount_paid DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  payment_status ENUM('unpaid','partial','paid') NOT NULL DEFAULT 'unpaid',
  security_deposit_required DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('active','completed','cancelled') NOT NULL DEFAULT 'active',
  is_complimentary TINYINT(1) NOT NULL DEFAULT 0,
  complimentary_reason VARCHAR(1000) NULL,
  complimentary_by INT UNSIGNED NULL,
  complimentary_at DATETIME NULL,
  final_billing_notes TEXT NULL,
  final_billed_at DATETIME NULL,
  final_billed_by INT UNSIGNED NULL,
  original_end_date DATE NULL,
  early_end_reason VARCHAR(255) NULL,
  early_ended_at DATETIME NULL,
  early_ended_by INT UNSIGNED NULL,
  notes TEXT NULL,
  cancelled_reason VARCHAR(255) NULL,
  completed_at DATETIME NULL,
  legacy_food_stall_rental_id BIGINT UNSIGNED NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_rental_reference (reference_no),
  UNIQUE KEY uq_rental_legacy_food_stall (legacy_food_stall_rental_id),
  KEY idx_rental_dates (start_date,end_date),
  KEY idx_rental_status (status,start_date,end_date),
  KEY idx_rental_billing (billing_mode,status),
  CONSTRAINT fk_rental_created_admin FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL,
  CONSTRAINT fk_rental_complimentary_admin FOREIGN KEY (complimentary_by) REFERENCES admins(id) ON DELETE SET NULL,
  CONSTRAINT fk_rental_final_admin FOREIGN KEY (final_billed_by) REFERENCES admins(id) ON DELETE SET NULL,
  CONSTRAINT fk_rental_early_admin FOREIGN KEY (early_ended_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rental_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  rental_id BIGINT UNSIGNED NOT NULL,
  rentable_id INT UNSIGNED NOT NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  agreed_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  notes VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_rental_item_rental (rental_id),
  KEY idx_rental_item_rentable (rentable_id,rental_id),
  CONSTRAINT fk_rental_item_rental FOREIGN KEY (rental_id) REFERENCES rentals(id) ON DELETE CASCADE,
  CONSTRAINT fk_rental_item_rentable FOREIGN KEY (rentable_id) REFERENCES rentables(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rental_dates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  rental_id BIGINT UNSIGNED NOT NULL,
  rental_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'scheduled',
  released_at DATETIME NULL,
  released_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_rental_date (rental_id,rental_date),
  KEY idx_rental_dates_date (rental_date,status),
  KEY idx_rental_dates_rental (rental_id,status,rental_date),
  CONSTRAINT fk_rental_date_rental FOREIGN KEY (rental_id) REFERENCES rentals(id) ON DELETE CASCADE,
  CONSTRAINT fk_rental_date_admin FOREIGN KEY (released_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rental_payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  rental_id BIGINT UNSIGNED NOT NULL,
  transaction_type VARCHAR(20) NOT NULL DEFAULT 'payment',
  amount DECIMAL(12,2) NOT NULL,
  payment_method VARCHAR(80) NOT NULL,
  payment_reference VARCHAR(120) NULL,
  notes TEXT NULL,
  recorded_by INT UNSIGNED NULL,
  paid_at DATETIME NOT NULL,
  legacy_food_stall_payment_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_rental_payment_legacy_food_stall (legacy_food_stall_payment_id),
  KEY idx_rental_payment_rental (rental_id,paid_at),
  KEY idx_rental_payment_admin (recorded_by),
  CONSTRAINT fk_rental_payment_rental FOREIGN KEY (rental_id) REFERENCES rentals(id) ON DELETE CASCADE,
  CONSTRAINT fk_rental_payment_admin FOREIGN KEY (recorded_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rental_deposit_transactions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  rental_id BIGINT UNSIGNED NOT NULL,
  transaction_type ENUM('receipt','refund') NOT NULL DEFAULT 'receipt',
  amount DECIMAL(12,2) NOT NULL,
  payment_method VARCHAR(80) NOT NULL,
  payment_reference VARCHAR(120) NULL,
  notes TEXT NULL,
  recorded_by INT UNSIGNED NULL,
  transacted_at DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_rental_deposit_rental (rental_id,transacted_at),
  CONSTRAINT fk_rental_deposit_rental FOREIGN KEY (rental_id) REFERENCES rentals(id) ON DELETE CASCADE,
  CONSTRAINT fk_rental_deposit_admin FOREIGN KEY (recorded_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rental_extensions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  rental_id BIGINT UNSIGNED NOT NULL,
  schedule_type VARCHAR(20) NOT NULL DEFAULT 'continuous',
  previous_end_date DATE NOT NULL,
  new_end_date DATE NOT NULL,
  previous_rental_amount DECIMAL(12,2) NOT NULL,
  new_rental_amount DECIMAL(12,2) NOT NULL,
  added_dates TEXT NULL,
  reason VARCHAR(1000) NOT NULL,
  extended_by INT UNSIGNED NULL,
  extended_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  legacy_food_stall_extension_id BIGINT UNSIGNED NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_rental_extension_legacy_food_stall (legacy_food_stall_extension_id),
  KEY idx_rental_extension_rental (rental_id,extended_at),
  KEY idx_rental_extension_admin (extended_by),
  CONSTRAINT fk_rental_extension_rental FOREIGN KEY (rental_id) REFERENCES rentals(id) ON DELETE CASCADE,
  CONSTRAINT fk_rental_extension_admin FOREIGN KEY (extended_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rental_charge_types (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(120) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_rental_charge_type_code (code),
  UNIQUE KEY uq_rental_charge_type_name (name),
  CONSTRAINT fk_rental_charge_type_admin FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rental_billing_periods (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  rental_id BIGINT UNSIGNED NOT NULL,
  period_no INT UNSIGNED NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  due_date DATE NOT NULL,
  rent_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  finalized_at DATETIME NULL,
  finalized_by INT UNSIGNED NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_rental_period (rental_id,period_no),
  KEY idx_rental_period_dates (period_start,period_end),
  KEY idx_rental_period_rental (rental_id,period_start),
  CONSTRAINT fk_rental_period_rental FOREIGN KEY (rental_id) REFERENCES rentals(id) ON DELETE CASCADE,
  CONSTRAINT fk_rental_period_admin FOREIGN KEY (finalized_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rental_charges (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  rental_id BIGINT UNSIGNED NOT NULL,
  billing_period_id BIGINT UNSIGNED NULL,
  charge_type_id INT UNSIGNED NOT NULL,
  description VARCHAR(255) NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  charged_at DATETIME NOT NULL,
  created_by INT UNSIGNED NULL,
  legacy_source VARCHAR(100) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_rental_charge_legacy (legacy_source),
  KEY idx_rental_charge_rental (rental_id,charged_at),
  KEY idx_rental_charge_period (billing_period_id),
  KEY idx_rental_charge_type (charge_type_id),
  CONSTRAINT fk_rental_charge_rental FOREIGN KEY (rental_id) REFERENCES rentals(id) ON DELETE CASCADE,
  CONSTRAINT fk_rental_charge_period FOREIGN KEY (billing_period_id) REFERENCES rental_billing_periods(id) ON DELETE CASCADE,
  CONSTRAINT fk_rental_charge_type FOREIGN KEY (charge_type_id) REFERENCES rental_charge_types(id) ON DELETE RESTRICT,
  CONSTRAINT fk_rental_charge_admin FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
