<?php
/**
 * FILE PURPOSE: Admin CRUD screen for website announcements and publication dates.
 * DEBUGGING: POST requests are CSRF-protected. Check the announcements table and flash messages when saves/deletes fail.
 */
require_once __DIR__ . '/../includes/functions.php';admin_required();$adminPageTitle='Announcements';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'save';
 try{if($action==='delete'){$stmt=db()->prepare('DELETE FROM announcements WHERE id=?');$stmt->execute([(int)$_POST['id']]);flash('success','Announcement deleted.');}else{$id=(int)($_POST['id']??0);$title=trim($_POST['title']??'');$body=trim($_POST['body']??'');$start=$_POST['publish_start']?:null;$end=$_POST['publish_end']?:null;$active=isset($_POST['is_active'])?1:0;if($title===''||$body==='')throw new RuntimeException('Title and message are required.');if($id){$stmt=db()->prepare('UPDATE announcements SET title=?,body=?,publish_start=?,publish_end=?,is_active=? WHERE id=?');$stmt->execute([$title,$body,$start,$end,$active,$id]);}else{$stmt=db()->prepare('INSERT INTO announcements(title,body,publish_start,publish_end,is_active) VALUES(?,?,?,?,?)');$stmt->execute([$title,$body,$start,$end,$active]);}flash('success','Announcement saved.');}}catch(Throwable $e){flash('danger',$e instanceof RuntimeException?$e->getMessage():'Unable to save announcement.');}redirect('announcements.php');
}
$edit=null;if(isset($_GET['edit'])){try{$stmt=db()->prepare('SELECT * FROM announcements WHERE id=?');$stmt->execute([(int)$_GET['edit']]);$edit=$stmt->fetch();}catch(Throwable $e){}}
try{$items=db()->query('SELECT * FROM announcements ORDER BY created_at DESC')->fetchAll();}catch(Throwable $e){$items=[];}
include __DIR__ . '/_header.php';
?>
<div class="admin-grid"><section class="panel"><div class="panel-head"><h2>Published Announcements</h2></div><div class="table-wrap"><table class="admin-table mobile-card-table"><thead><tr><th>Title</th><th>Publication</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($items as $item): ?><tr><td data-label="Announcement" data-priority="primary"><strong><?= e($item['title']) ?></strong><br><span class="small muted"><?= e(text_excerpt((string)$item['body'], 90)) ?></span></td><td data-label="Publication"><?= e($item['publish_start']?:'Immediate') ?> – <?= e($item['publish_end']?:'No end') ?></td><td data-label="Status"><span class="status-pill status-<?= $item['is_active']?'success':'secondary' ?>"><?= $item['is_active']?'Active':'Hidden' ?></span></td><td data-label="Actions"><div class="admin-actions"><a class="btn btn-outline btn-sm" href="?edit=<?= (int)$item['id'] ?>">Edit</a><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$item['id'] ?>"><button class="btn btn-danger btn-sm" data-confirm="Delete this announcement?">Delete</button></form></div></td></tr><?php endforeach; ?></tbody></table></div></section><aside class="panel"><h2><?= $edit?'Edit':'New' ?> Announcement</h2><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><div class="form-group" style="margin-bottom:12px"><label>Title</label><input name="title" value="<?= e($edit['title']??'') ?>" required></div><div class="form-group" style="margin-bottom:12px"><label>Message</label><textarea name="body" required><?= e($edit['body']??'') ?></textarea></div><div class="form-group" style="margin-bottom:12px"><label>Publish Start</label><input type="date" name="publish_start" value="<?= e($edit['publish_start']??'') ?>"></div><div class="form-group" style="margin-bottom:12px"><label>Publish End</label><input type="date" name="publish_end" value="<?= e($edit['publish_end']??'') ?>"></div><label style="display:flex;gap:8px;margin-bottom:18px"><input type="checkbox" name="is_active" style="width:auto" <?= !isset($edit['is_active'])||$edit['is_active']?'checked':'' ?>> Show on website</label><button class="btn btn-primary btn-block">Save Announcement</button><?php if($edit): ?><a class="btn btn-outline btn-block" style="margin-top:8px" href="announcements.php">Cancel Edit</a><?php endif; ?></form></aside></div>
<?php include __DIR__ . '/_footer.php'; ?>
