<?php
require_once __DIR__ . '/../includes/functions.php';
admin_required();
if(!is_admin()){http_response_code(403);exit('Administrator access required.');}
$id=max(0,(int)($_GET['id']??0));$stmt=db()->prepare("SELECT r.*,a.full_name AS created_by_name FROM rentals r LEFT JOIN admins a ON a.id=r.created_by WHERE r.id=?");$stmt->execute([$id]);$r=$stmt->fetch();if(!$r){http_response_code(404);exit('Rental not found.');}
$items=rental_items_for($id);$dates=rental_dates_for($id,true);$payments=rental_payments_for($id);$depositTransactions=rental_deposit_transactions_for($id);$charges=rental_charges_for($id);$periods=rental_billing_periods($id);$cancellation=rental_cancellation_for($id);$paid=rental_payment_total($id);$total=rental_total_amount($r);$balance=$cancellation?0:max(0,$total-$paid);$depositRequired=max(0,(float)($r['security_deposit_required']??0));$depositHeld=rental_deposit_held($id);
$ext=db()->prepare("SELECT x.*,a.full_name AS extended_by_name FROM rental_extensions x LEFT JOIN admins a ON a.id=x.extended_by WHERE x.rental_id=? ORDER BY x.extended_at,x.id");$ext->execute([$id]);$extensions=$ext->fetchAll();
?><!doctype html><html><head><meta charset="utf-8"><title><?= e($r['reference_no']) ?> Rental</title><style>
@page{size:Letter;margin:12mm}*{box-sizing:border-box}body{font:12px Arial,sans-serif;color:#111;margin:0}.toolbar{display:flex;gap:8px;justify-content:flex-end;margin-bottom:12px}.btn{border:1px solid #222;background:#fff;padding:8px 12px;border-radius:6px;cursor:pointer}.sheet{max-width:190mm;margin:auto}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:2px solid #111;padding-bottom:10px}.head h1{font-size:22px;margin:0}.muted{color:#666}.badge{display:inline-block;padding:4px 8px;border:1px solid #333;border-radius:999px;font-weight:700}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.box{border:1px solid #bbb;border-radius:8px;padding:12px}.box h2{font-size:13px;margin:0 0 10px;text-transform:uppercase}.kv{display:grid;grid-template-columns:140px 1fr;gap:6px 10px}.kv span{color:#666}.summary{display:grid;grid-template-columns:1fr auto;gap:7px}.summary .total{border-top:1px solid #aaa;padding-top:7px;font-weight:700}table{width:100%;border-collapse:collapse;margin-top:8px}th,td{border:1px solid #bbb;padding:6px;text-align:left;vertical-align:top}th{background:#f2f2f2}.section{margin-top:14px}.section h2{font-size:14px;margin:0 0 6px}.chips{display:flex;flex-wrap:wrap;gap:5px}.chip{border:1px solid #bbb;border-radius:999px;padding:4px 7px}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:50px;margin-top:36px}.sig{border-top:1px solid #222;padding-top:6px;text-align:center}@media print{.toolbar{display:none}.sheet{max-width:none}.box{break-inside:avoid}.section{break-inside:auto}}
</style></head><body><div class="toolbar"><button class="btn" onclick="window.print()">Print</button><button class="btn" onclick="window.close()">Close</button></div><main class="sheet">
<div class="head"><div><h1>THE LEISURE HUB</h1><div class="muted">Rental Record</div></div><div style="text-align:right"><strong><?= e($r['reference_no']) ?></strong><br><span class="badge"><?= e(rental_lifecycle($r)) ?></span><?php if($r['is_complimentary']):?><br><span class="badge" style="margin-top:5px">COMPLIMENTARY</span><?php endif;?></div></div>
<div class="grid"><section class="box"><h2>Client & Schedule</h2><div class="kv"><span>Client / Tenant</span><strong><?= e($r['client_name']) ?></strong><span>Contact</span><strong><?= e($r['contact_number']?:'—') ?></strong><span>Organization</span><strong><?= e($r['organization']?:'—') ?></strong><span>Billing</span><strong><?= $r['billing_mode']==='monthly'?'Monthly Recurring':'One-time / Agreed' ?></strong><span>Schedule</span><strong><?= $r['schedule_type']==='flexible'?'Flexible Dates':'Continuous' ?></strong><span>Period</span><strong><?= date('M j, Y',strtotime($r['start_date'])) ?> – <?= date('M j, Y',strtotime($r['end_date'])) ?></strong></div></section><section class="box"><h2>Financial Summary</h2><div class="summary">
<?php if($cancellation): ?><span>Original Total</span><strong><?= money((float)$cancellation['original_total']) ?></strong><span>Paid Before Cancellation</span><strong><?= money((float)$cancellation['paid_before_cancellation']) ?></strong><span>Refunded</span><strong><?= money((float)$cancellation['refund_amount']) ?></strong><span class="total">TLH Retained</span><strong class="total"><?= money((float)$cancellation['retained_amount']) ?></strong><span>Balance</span><strong><?= money(0) ?></strong><?php else: ?><span>Base Rental</span><strong><?= money((float)$r['base_amount']) ?></strong><span>Additional Charges</span><strong><?= money(rental_charge_total($id)) ?></strong><span class="total">Total Due</span><strong class="total"><?= money($total) ?></strong><span>Paid</span><strong><?= money($paid) ?></strong><span>Balance</span><strong><?= money($balance) ?></strong><?php endif; ?><?php if($depositRequired>0.009||$depositHeld>0.009): ?><span>Security Deposit Required</span><strong><?= money($depositRequired) ?></strong><span>Deposit Held</span><strong><?= money($depositHeld) ?></strong><?php endif; ?></div><?php if($depositRequired>0.009||$depositHeld>0.009): ?><p class="muted" style="font-size:10px;margin:8px 0 0">Security Deposit is separate from Sales and rental payments.</p><?php endif; ?></section></div>
<section class="section"><h2>Rentables</h2><table><thead><tr><th>Code / Name</th><th>Category</th><th>Location</th><th>Qty</th><th>Agreed Amount</th></tr></thead><tbody><?php foreach($items as $it):?><tr><td><strong><?= e($it['code']) ?></strong><br><?= e($it['name']) ?></td><td><?= e($it['category_name']) ?></td><td><?= e($it['location']?:'—') ?></td><td><?= (int)$it['quantity'] ?></td><td><?= money((float)$it['agreed_amount']) ?><?= $r['billing_mode']==='monthly'?' / month':'' ?></td></tr><?php endforeach;?></tbody></table></section>
<?php if($r['schedule_type']==='flexible'):?><section class="section"><h2>Flexible Rental Dates</h2><div class="chips"><?php foreach($dates as $d):?><span class="chip"><?= date('M j, Y',strtotime($d['rental_date'])) ?><?= $d['status']!=='scheduled'?' · Released':'' ?></span><?php endforeach;?></div></section><?php endif;?>
<?php if($periods):?><section class="section"><h2>Monthly Billing Periods</h2><table><thead><tr><th>Period</th><th>Dates</th><th>Rent</th><th>Additional Charges</th><th>Status</th></tr></thead><tbody><?php foreach($periods as $bp):?><tr><td>#<?= (int)$bp['period_no'] ?></td><td><?= date('M j',strtotime($bp['period_start'])) ?> – <?= date('M j, Y',strtotime($bp['period_end'])) ?></td><td><?= money((float)$bp['rent_amount']) ?></td><td><?= money((float)$bp['charge_total']) ?></td><td><?= $bp['finalized_at']?'Finalized':'Open' ?></td></tr><?php endforeach;?></tbody></table></section><?php endif;?>
<?php if($charges):?><section class="section"><h2>Additional Charges</h2><table><thead><tr><th>Date</th><th>Description</th><th>Period</th><th>Amount</th></tr></thead><tbody><?php foreach($charges as $c):?><tr><td><?= date('M j, Y',strtotime($c['charged_at'])) ?></td><td><?= e($c['description']?:$c['charge_type_name']) ?></td><td><?= $c['period_no']?'#'.(int)$c['period_no']:'Rental' ?></td><td><?= money((float)$c['amount']) ?></td></tr><?php endforeach;?></tbody></table></section><?php endif;?>
<section class="section"><h2>Payment / Refund History</h2><table><thead><tr><th>Type</th><th>Date</th><th>Method</th><th>Reference</th><th>Details</th><th>Amount</th></tr></thead><tbody><?php foreach($payments as $p): $isRefund=(string)($p['transaction_type']??'payment')==='refund'||(float)$p['amount']<0; ?><tr><td><?= $isRefund?'Refund':'Payment' ?></td><td><?= date('M j, Y g:i A',strtotime($p['paid_at'])) ?></td><td><?= e(booking_payment_method_label($p['payment_method'])) ?></td><td><?= e($p['payment_reference']?:'—') ?></td><td><?= e($p['notes']?:($isRefund?'Refund':'Payment')) ?></td><td><?= money((float)$p['amount']) ?></td></tr><?php endforeach;?><?php if(!$payments):?><tr><td colspan="6">No payments recorded.</td></tr><?php endif;?></tbody></table></section>
<?php if($depositTransactions):?><section class="section"><h2>Security Deposit History</h2><table><thead><tr><th>Date</th><th>Type</th><th>Method</th><th>Reference</th><th>Amount</th></tr></thead><tbody><?php foreach($depositTransactions as $d):?><tr><td><?= date('M j, Y g:i A',strtotime($d['transacted_at'])) ?></td><td><?= $d['transaction_type']==='refund'?'Refund':'Receipt' ?></td><td><?= e(booking_payment_method_label($d['payment_method'])) ?></td><td><?= e($d['payment_reference']?:'—') ?></td><td><?= $d['transaction_type']==='refund'?'-':'' ?><?= money((float)$d['amount']) ?></td></tr><?php endforeach;?></tbody></table></section><?php endif;?>
<?php if($extensions):?><section class="section"><h2>Extension History</h2><table><thead><tr><th>Date</th><th>Change</th><th>Amount</th><th>Reason</th></tr></thead><tbody><?php foreach($extensions as $x):?><tr><td><?= date('M j, Y',strtotime($x['extended_at'])) ?></td><td><?= date('M j',strtotime($x['previous_end_date'])) ?> → <?= date('M j, Y',strtotime($x['new_end_date'])) ?><?= $x['added_dates']?'<br>'.e($x['added_dates']):'' ?></td><td><?= money((float)$x['previous_rental_amount']) ?> → <?= money((float)$x['new_rental_amount']) ?></td><td><?= e($x['reason']) ?></td></tr><?php endforeach;?></tbody></table></section><?php endif;?>
<?php if($cancellation):?><section class="section box"><h2>Cancellation Settlement</h2><div class="kv"><span>Cancelled At</span><strong><?= date('M j, Y g:i A',strtotime($cancellation['cancelled_at'])) ?></strong><span>Cancelled By</span><strong><?= e($cancellation['cancelled_by_name']?:'Administrator') ?></strong><span>Reason</span><strong><?= e($cancellation['cancellation_reason']) ?></strong><span>Refund</span><strong><?= money((float)$cancellation['refund_amount']) ?><?= !empty($cancellation['refund_method'])?' via '.e(booking_payment_method_label($cancellation['refund_method'])):'' ?></strong><span>TLH Retained</span><strong><?= money((float)$cancellation['retained_amount']) ?></strong></div></section><?php endif;?>
<?php if($r['is_complimentary']):?><section class="section box"><h2>Complimentary Rental</h2><p><?= nl2br(e($r['complimentary_reason']?:'For record purposes only.')) ?></p></section><?php endif;?>
<?php if(!empty($r['notes'])):?><section class="section box"><h2>Notes</h2><p><?= nl2br(e($r['notes'])) ?></p></section><?php endif;?>
<div class="signatures"><div class="sig">Prepared By / Administrator</div><div class="sig">Client / Tenant</div></div>
</main></body></html>
