<?php
require_once __DIR__ . '/../includes/functions.php';
admin_required();
if(!is_admin()){flash('danger','Administrator access is required to permanently delete rentals.');redirect('rentals.php');}
$rentalId=(int)($_GET['id']??$_POST['rental_id']??0);$returnTo=trim((string)($_GET['return_to']??$_POST['return_to']??'rentals.php'));
if($returnTo===''||preg_match('~[\r\n]~',$returnTo)||parse_url($returnTo,PHP_URL_SCHEME)!==null||parse_url($returnTo,PHP_URL_HOST)!==null||str_starts_with($returnTo,'/')||str_starts_with($returnTo,'../'))$returnTo='rentals.php';
if($rentalId<1){flash('danger','Invalid rental delete request.');redirect($returnTo);}
$load=static function(int $id){$stmt=db()->prepare("SELECT r.*,COALESCE((SELECT SUM(p.amount) FROM rental_payments p WHERE p.rental_id=r.id),0) AS ledger_amount_paid,(SELECT COUNT(*) FROM rental_payments p2 WHERE p2.rental_id=r.id) AS payment_count,(SELECT COUNT(*) FROM rental_deposit_transactions d WHERE d.rental_id=r.id) AS deposit_transaction_count FROM rentals r WHERE r.id=? LIMIT 1");$stmt->execute([$id]);return $stmt->fetch();};
$rental=$load($rentalId);if(!$rental){flash('danger','Rental not found.');redirect($returnTo);}
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$password=(string)($_POST['admin_password']??'');$pdo=null;$recordLockHeld=false;
 try{
  if($password==='')throw new RuntimeException('Enter your administrator password to confirm permanent deletion.');$admin=current_admin();if(!$admin||(int)($admin['id']??0)<1)throw new RuntimeException('Your administrator session could not be verified.');
  $accountStmt=db()->prepare('SELECT id,role,is_active,password_hash FROM admins WHERE id=? LIMIT 1');$accountStmt->execute([(int)$admin['id']]);$account=$accountStmt->fetch();if(!$account||empty($account['is_active'])||(string)$account['role']!=='admin'||!password_verify($password,(string)$account['password_hash']))throw new RuntimeException('Incorrect administrator password. The rental was not deleted.');
  if(!rental_record_lock_acquire($rentalId,10))throw new RuntimeException('This rental is being updated by another administrator. Please try again.');$recordLockHeld=true;
  $pdo=db();$pdo->beginTransaction();$locked=$pdo->prepare('SELECT * FROM rentals WHERE id=? FOR UPDATE');$locked->execute([$rentalId]);$row=$locked->fetch();if(!$row)throw new RuntimeException('Rental not found.');
  $ps=$pdo->prepare('SELECT COUNT(*) payment_count,COALESCE(SUM(amount),0) ledger_total FROM rental_payments WHERE rental_id=?');$ps->execute([$rentalId]);$sum=$ps->fetch()?:['payment_count'=>0,'ledger_total'=>0];$ref=(string)$row['reference_no'];
  $pdo->prepare('DELETE FROM rental_payments WHERE rental_id=?')->execute([$rentalId]);$pdo->prepare('DELETE FROM rental_deposit_transactions WHERE rental_id=?')->execute([$rentalId]);$del=$pdo->prepare('DELETE FROM rentals WHERE id=?');$del->execute([$rentalId]);if($del->rowCount()!==1)throw new RuntimeException('The rental could not be deleted.');$pdo->commit();
  $message='Rental '.$ref.' was permanently deleted.';if((int)$sum['payment_count']>0)$message.=' '.(int)$sum['payment_count'].' payment transaction'.((int)$sum['payment_count']===1?'':'s').' totaling '.money(abs((float)$sum['ledger_total'])).' net were also removed.';if($recordLockHeld){rental_record_lock_release($rentalId);$recordLockHeld=false;}flash('success',$message);redirect($returnTo);
 }catch(Throwable $e){if($pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();if($recordLockHeld)rental_record_lock_release($rentalId);flash('danger',$e instanceof RuntimeException?$e->getMessage():'The rental could not be deleted.');redirect('rental-delete.php?id='.$rentalId.'&return_to='.rawurlencode($returnTo));}
}
$totalDue=rental_total_amount($rental);$ledger=(float)$rental['ledger_amount_paid'];$items=rental_item_summary($rentalId,5);$adminPageTitle='Delete Rental';include __DIR__ . '/_header.php';
?>
<div class="admin-grid reservation-delete-grid"><section class="panel reservation-delete-panel"><div class="panel-head"><div><span class="small muted">Rental <?= e($rental['reference_no']) ?></span><h2>Permanent Delete</h2></div><a class="btn btn-outline btn-sm" href="rental-view.php?id=<?= $rentalId ?>">Back to Rental</a></div>
<div class="alert alert-danger reservation-delete-warning"><strong>This action cannot be undone.</strong> The rental, rentable lines, dates, charges, billing periods, extension history, and all payment/deposit history will be permanently removed.</div>
<div class="reservation-delete-summary"><div><span>Client</span><strong><?= e($rental['client_name']) ?></strong></div><div><span>Rentables</span><strong><?= e($items) ?></strong></div><div><span>Rental Period</span><strong><?= date('M j, Y',strtotime($rental['start_date'])) ?> – <?= date('M j, Y',strtotime($rental['end_date'])) ?></strong></div><div><span>Billing</span><strong><?= $rental['billing_mode']==='monthly'?'Monthly recurring':'One-time' ?></strong></div><div><span>Total Rental Value</span><strong><?= money($totalDue) ?></strong></div><div><span>Payment Transactions</span><strong><?= (int)$rental['payment_count'] ?></strong></div><div><span>Deposit Transactions</span><strong><?= (int)$rental['deposit_transaction_count'] ?></strong></div><div class="reservation-delete-sales-impact"><span>Net Collections Removed</span><strong><?= money($ledger) ?></strong></div></div>
<form method="post" class="reservation-delete-form" data-permanent-delete-form><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="rental_id" value="<?= $rentalId ?>"><input type="hidden" name="return_to" value="<?= e($returnTo) ?>"><div class="form-group"><label>Administrator Password</label><input type="password" name="admin_password" autocomplete="current-password" required autofocus><span class="field-help">Enter the password of the administrator account currently signed in.</span></div><div class="reservation-delete-actions"><a class="btn btn-outline" href="rental-view.php?id=<?= $rentalId ?>">Cancel</a><button class="btn btn-danger">Permanently Delete Rental &amp; Financial History</button></div></form></section></div>
<script>(function(){var f=document.querySelector('[data-permanent-delete-form]');if(f)f.addEventListener('submit',function(e){if(!confirm('Permanently delete rental <?= e($rental['reference_no']) ?> and all related financial history? This cannot be undone.'))e.preventDefault();});}());</script>
<?php include __DIR__ . '/_footer.php'; ?>
