<?php
require_once __DIR__ . '/../includes/functions.php';
admin_required();
if(!is_admin()){flash('danger','Administrator access is required.');redirect('index.php');}
$id=max(0,(int)($_GET['id']??$_POST['id']??0));
$stmt=db()->prepare('SELECT * FROM rentals WHERE id=?');$stmt->execute([$id]);$rental=$stmt->fetch();
if(!$rental){flash('danger','Rental not found.');redirect('rentals.php');}
if($rental['status']!=='active'||!empty($rental['early_ended_at'])||!empty($rental['final_billed_at'])||$rental['end_date']<date('Y-m-d')){flash('warning','This rental can no longer be extended.');redirect('rental-view.php?id='.$id);}
$items=rental_items_for($id);$adminPageTitle='Extend Rental';$errors=[];$currentTotal=rental_total_amount($rental);$currentPaid=rental_payment_total($id);$currentMonthlyRate=0.0;foreach($items as $it)$currentMonthlyRate+=(float)$it['agreed_amount'];
$extensionDates=[];$validDate=static function(string $v):bool{$d=DateTimeImmutable::createFromFormat('!Y-m-d',$v);return $d!==false&&$d->format('Y-m-d')===$v;};
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$reason=trim((string)($_POST['reason']??''));$recordPayment=isset($_POST['record_extension_payment']);$paymentAmount=is_numeric($_POST['payment_amount']??null)?round((float)$_POST['payment_amount'],2):0;$method=(string)($_POST['payment_method']??'Cash');$reference=trim((string)($_POST['payment_reference']??''));$paidAt=(string)($_POST['paid_at']??'');
 if($reason==='')$errors[]='Enter the reason for the extension.';
 $newEnd=$rental['end_date'];$extensionCharge=0.0;$monthlyRate=$currentMonthlyRate;$requestDates=[];
 if($rental['billing_mode']==='monthly'){
   $newEnd=trim((string)($_POST['new_end_date']??''));$monthlyRate=is_numeric($_POST['monthly_extension_rate']??null)?round((float)$_POST['monthly_extension_rate'],2):-1;
   if(!$validDate($newEnd)||$newEnd<=$rental['end_date'])$errors[]='New end date must be a valid date later than the current end date.';if($monthlyRate<0)$errors[]='Enter a valid monthly rent for the extension.';
   if(!$errors)$requestDates=rental_schedule_dates('continuous',(new DateTimeImmutable($rental['end_date']))->modify('+1 day')->format('Y-m-d'),$newEnd,[]);
 }elseif($rental['schedule_type']==='flexible'){
   foreach((array)($_POST['extension_dates']??[]) as $d){$d=trim((string)$d);$p=DateTimeImmutable::createFromFormat('!Y-m-d',$d);if($p&&$p->format('Y-m-d')===$d&&$d>$rental['end_date'])$extensionDates[$d]=$d;}ksort($extensionDates);$extensionDates=array_values($extensionDates);if(!$extensionDates)$errors[]='Add at least one extension date after the current last rental date.';else{$newEnd=$extensionDates[count($extensionDates)-1];$requestDates=$extensionDates;}
   $extensionCharge=is_numeric($_POST['extension_charge']??null)?round((float)$_POST['extension_charge'],2):-1;if($extensionCharge<0)$errors[]='Enter a valid extension charge. Use 0.00 when the extension is free.';
 }else{
   $newEnd=trim((string)($_POST['new_end_date']??''));if(!$validDate($newEnd)||$newEnd<=$rental['end_date'])$errors[]='New end date must be a valid date later than the current end date.';$extensionCharge=is_numeric($_POST['extension_charge']??null)?round((float)$_POST['extension_charge'],2):-1;if($extensionCharge<0)$errors[]='Enter a valid extension charge.';if(!$errors)$requestDates=rental_schedule_dates('continuous',(new DateTimeImmutable($rental['end_date']))->modify('+1 day')->format('Y-m-d'),$newEnd,[]);
 }
 if(!$errors){$requested=[];foreach($items as $it)$requested[]=['rentable_id'=>(int)$it['rentable_id'],'quantity'=>(int)$it['quantity']];$errors=array_merge($errors,rental_availability_errors($requested,'flexible',$requestDates[0]??'',$requestDates[count($requestDates)-1]??'',$requestDates,$id));}
 if($recordPayment){if($paymentAmount<=0)$errors[]='Enter the extension payment amount.';if(!in_array($method,booking_payment_methods(),true))$errors[]='Choose a valid payment method.';if($method!=='Cash'&&$reference==='')$errors[]='Enter a reference or OR number for non-cash payment.';if(!strtotime($paidAt))$errors[]='Enter a valid payment date and time.';}
 if(!$errors){$availabilityLockHeld=false;$recordLockHeld=false;try{
   $pdo=db();if(!rental_availability_lock_acquire(10))throw new RuntimeException('Another rental update is being processed. Please try again in a few seconds.');$availabilityLockHeld=true;if(!rental_record_lock_acquire($id,10))throw new RuntimeException('This rental is being updated by another administrator. Please try again.');$recordLockHeld=true;
   $lockedErrors=rental_availability_errors($requested,'flexible',$requestDates[0]??'',$requestDates[count($requestDates)-1]??'',$requestDates,$id);if($lockedErrors)throw new RuntimeException(implode(' ',array_unique($lockedErrors)));
   $pdo->beginTransaction();$rowLock=$pdo->prepare('SELECT * FROM rentals WHERE id=? FOR UPDATE');$rowLock->execute([$id]);$lockedRental=$rowLock->fetch();if(!$lockedRental)throw new RuntimeException('Rental not found.');if($lockedRental['status']!=='active'||!empty($lockedRental['early_ended_at'])||!empty($lockedRental['final_billed_at'])||$lockedRental['end_date']!==$rental['end_date'])throw new RuntimeException('The rental changed while this page was open. Reload it and try the extension again.');$previousEnd=$lockedRental['end_date'];$previousTotal=rental_total_amount($lockedRental);
   if($lockedRental['billing_mode']==='monthly'){
      $start=(new DateTimeImmutable($previousEnd))->modify('+1 day');$end=DateTimeImmutable::createFromFormat('!Y-m-d',$newEnd);$periodNo=(int)$pdo->query('SELECT COALESCE(MAX(period_no),0) FROM rental_billing_periods WHERE rental_id='.(int)$id)->fetchColumn()+1;$ins=$pdo->prepare('INSERT INTO rental_billing_periods(rental_id,period_no,period_start,period_end,due_date,rent_amount) VALUES(?,?,?,?,?,?)');$cursor=$start;$anchorDay=(int)(new DateTimeImmutable($lockedRental['start_date']))->format('j');while($cursor<=$end&&$periodNo<=240){$next=rental_next_month_anchor($cursor,$anchorDay);$pe=$next->modify('-1 day');if($pe>$end)$pe=$end;$ins->execute([$id,$periodNo,$cursor->format('Y-m-d'),$pe->format('Y-m-d'),$cursor->format('Y-m-d'),$monthlyRate]);$periodNo++;$cursor=$pe->modify('+1 day');}$pdo->prepare('UPDATE rentals SET end_date=? WHERE id=?')->execute([$newEnd,$id]);rental_recalculate_header($id);
   }else{
      if($lockedRental['schedule_type']==='flexible'){$di=$pdo->prepare("INSERT INTO rental_dates(rental_id,rental_date,status) VALUES(?,?,'scheduled')");foreach($extensionDates as $d)$di->execute([$id,$d]);}$pdo->prepare('UPDATE rentals SET end_date=? WHERE id=?')->execute([$newEnd,$id]);if($extensionCharge!=0.0){$typeId=rental_charge_type_id('extension');$ci=$pdo->prepare('INSERT INTO rental_charges(rental_id,charge_type_id,description,amount,charged_at,created_by) VALUES(?,?,?,?,NOW(),?)');$ci->execute([$id,$typeId,'Rental Extension Charge',$extensionCharge,current_admin()['id']]);}rental_recalculate_header($id);
   }
   $updated=rental_by_id($id);$newTotal=rental_total_amount($updated);$audit=$pdo->prepare('INSERT INTO rental_extensions(rental_id,schedule_type,previous_end_date,new_end_date,previous_rental_amount,new_rental_amount,added_dates,reason,extended_by) VALUES(?,?,?,?,?,?,?,?,?)');$audit->execute([$id,$lockedRental['schedule_type'],$previousEnd,$newEnd,$previousTotal,$newTotal,$extensionDates?implode(', ',$extensionDates):null,$reason,current_admin()['id']]);
   $balance=max(0,$newTotal-rental_payment_total($id));if($recordPayment){if($paymentAmount>$balance+0.001)throw new RuntimeException('Extension payment cannot exceed the new balance of '.money($balance).'.');$p=$pdo->prepare('INSERT INTO rental_payments(rental_id,amount,payment_method,payment_reference,notes,recorded_by,paid_at) VALUES(?,?,?,?,?,?,?)');$p->execute([$id,$paymentAmount,$method,$reference?:null,'Rental extension payment',current_admin()['id'],date('Y-m-d H:i:s',strtotime($paidAt))]);rental_recalculate_header($id);} $pdo->commit();rental_record_lock_release($id);$recordLockHeld=false;rental_availability_lock_release();$availabilityLockHeld=false;flash('success','Rental extended successfully.');redirect('rental-view.php?id='.$id);
 }catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();if($recordLockHeld)rental_record_lock_release($id);if($availabilityLockHeld)rental_availability_lock_release();$errors[]=$e instanceof RuntimeException?$e->getMessage():'Unable to extend rental.';}}
}
include __DIR__ . '/_header.php';
?>
<section class="panel"><div class="panel-head"><div><h2>Extend Rental</h2><p class="muted"><?= e($rental['reference_no']) ?> · <?= e($rental['client_name']) ?> · <?= e(rental_item_summary($id,4)) ?></p></div><a class="btn btn-outline btn-sm" href="rental-view.php?id=<?= $id ?>">Back to Rental</a></div>
<?php if($errors):?><div class="alert alert-danger"><ul><?php foreach($errors as $e):?><li><?= e($e) ?></li><?php endforeach;?></ul></div><?php endif;?>
<div class="rental-detail-grid"><div><div class="rental-info-grid"><div><span>Current End Date</span><strong><?= date('M j, Y',strtotime($rental['end_date'])) ?></strong></div><div><span>Current Total</span><strong><?= money($currentTotal) ?></strong></div><div><span>Paid</span><strong><?= money($currentPaid) ?></strong></div><div><span>Current Balance</span><strong><?= money(max(0,$currentTotal-$currentPaid)) ?></strong></div></div></div></div>
<form method="post" data-extension-form><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= $id ?>">
<?php if($rental['billing_mode']==='monthly'): ?><div class="form-grid"><div class="form-group"><label>New End Date *</label><input type="date" name="new_end_date" min="<?= e((new DateTimeImmutable($rental['end_date']))->modify('+1 day')->format('Y-m-d')) ?>" required></div><div class="form-group"><label>Monthly Rent for Extension *</label><input type="number" name="monthly_extension_rate" min="0" step="0.01" value="<?= e(number_format($currentMonthlyRate,2,'.','')) ?>" required><span class="field-help">Admin sets the monthly rate for the added billing periods.</span></div></div>
<?php elseif($rental['schedule_type']==='flexible'): ?><div class="form-group"><label>Extension Charge *</label><input type="number" name="extension_charge" min="0" step="0.01" value="0.00" required></div><div class="rental-flexible-toolbar"><div><strong>Add Extension Dates</strong><span class="field-help">Each date must be later than <?= date('M j, Y',strtotime($rental['end_date'])) ?>.</span></div><button class="btn btn-outline btn-sm" type="button" data-add-extension-date>+ Add Date</button></div><div data-extension-dates><?php foreach($extensionDates as $d):?><div class="rental-flexible-row"><input type="date" name="extension_dates[]" min="<?= e((new DateTimeImmutable($rental['end_date']))->modify('+1 day')->format('Y-m-d')) ?>" value="<?= e($d) ?>" required><button type="button" class="btn btn-outline btn-sm" data-remove-date>Remove</button></div><?php endforeach;?></div>
<?php else: ?><div class="form-grid"><div class="form-group"><label>New End Date *</label><input type="date" name="new_end_date" min="<?= e((new DateTimeImmutable($rental['end_date']))->modify('+1 day')->format('Y-m-d')) ?>" required></div><div class="form-group"><label>Extension Charge *</label><input type="number" name="extension_charge" min="0" step="0.01" value="0.00" required><span class="field-help">Enter the additional negotiated charge for the extension.</span></div></div><?php endif;?>
<div class="form-group admin-form-gap"><label>Reason *</label><textarea name="reason" required placeholder="Client requested extension"></textarea></div>
<label class="rental-payment-toggle"><input type="checkbox" name="record_extension_payment" value="1" data-ext-payment-toggle><span><strong>Record extension payment now</strong><small>The new payment remains a separate collection transaction.</small></span></label><div class="form-grid" data-ext-payment-fields hidden><div class="form-group"><label>Payment Amount *</label><input type="number" name="payment_amount" min="0.01" step="0.01"></div><div class="form-group"><label>Payment Method *</label><select name="payment_method" data-booking-payment-method><?php foreach(booking_payment_methods() as $m):?><option value="<?= e($m) ?>"><?= e(booking_payment_method_label($m)) ?></option><?php endforeach;?></select></div><div class="form-group"><label>Reference / OR</label><input name="payment_reference" maxlength="120" data-booking-payment-reference data-allow-cash-reference></div><div class="form-group"><label>Paid At *</label><input type="datetime-local" name="paid_at" value="<?= e(date('Y-m-d\TH:i')) ?>"></div></div>
<div class="rental-form-footer"><a class="btn btn-outline" href="rental-view.php?id=<?= $id ?>">Cancel</a><button class="btn btn-primary">Save Extension</button></div></form></section>
<script>(function(){var f=document.querySelector('[data-extension-form]');if(!f)return;var t=f.querySelector('[data-ext-payment-toggle]'),p=f.querySelector('[data-ext-payment-fields]');t.addEventListener('change',function(){p.hidden=!t.checked;});var add=f.querySelector('[data-add-extension-date]'),list=f.querySelector('[data-extension-dates]');if(add){function bind(b){b.addEventListener('click',function(){b.closest('.rental-flexible-row').remove();});}list.querySelectorAll('[data-remove-date]').forEach(bind);add.addEventListener('click',function(){var row=document.createElement('div');row.className='rental-flexible-row';row.innerHTML='<input type="date" name="extension_dates[]" min="<?= e((new DateTimeImmutable($rental['end_date']))->modify('+1 day')->format('Y-m-d')) ?>" required><button type="button" class="btn btn-outline btn-sm" data-remove-date>Remove</button>';list.appendChild(row);bind(row.querySelector('[data-remove-date]'));});}}());</script>
<?php include __DIR__ . '/_footer.php'; ?>
