<?php
require_once __DIR__ . '/../includes/functions.php';
admin_required();
if(!is_admin()){flash('danger','Administrator access is required.');redirect('index.php');}
$adminPageTitle='Rental Charge Types';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();try{$action=(string)($_POST['action']??'save');$id=(int)($_POST['id']??0);
  if($action==='delete'){$count=db()->prepare('SELECT COUNT(*) FROM rental_charges WHERE charge_type_id=?');$count->execute([$id]);if((int)$count->fetchColumn()>0)throw new RuntimeException('This charge type already has history. Set it inactive instead.');db()->prepare('DELETE FROM rental_charge_types WHERE id=?')->execute([$id]);flash('success','Charge type deleted.');}
  else{$name=trim((string)($_POST['name']??''));$code=strtolower(trim((string)($_POST['code']??'')));$active=isset($_POST['is_active'])?1:0;if($name==='')throw new RuntimeException('Enter a charge type name.');if($code==='')$code=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$name),'-'));if(!preg_match('/^[a-z0-9_-]{2,50}$/',$code))throw new RuntimeException('Use a simple code containing letters, numbers, hyphens, or underscores.');$dup=db()->prepare('SELECT COUNT(*) FROM rental_charge_types WHERE (name=? OR code=?) AND id<>?');$dup->execute([$name,$code,$id]);if((int)$dup->fetchColumn()>0)throw new RuntimeException('That charge type already exists.');if($id>0){db()->prepare('UPDATE rental_charge_types SET code=?,name=?,is_active=? WHERE id=?')->execute([$code,$name,$active,$id]);flash('success','Charge type updated.');}else{db()->prepare('INSERT INTO rental_charge_types(code,name,is_active,created_by) VALUES(?,?,?,?)')->execute([$code,$name,$active,current_admin()['id']]);flash('success','Charge type added.');}}
 }catch(Throwable $e){flash('danger',$e instanceof RuntimeException?$e->getMessage():'Unable to update charge type.');}redirect('rental-charge-types.php');
}
$edit=null;if(isset($_GET['edit'])){$stmt=db()->prepare('SELECT * FROM rental_charge_types WHERE id=?');$stmt->execute([(int)$_GET['edit']]);$edit=$stmt->fetch()?:null;}
$rows=db()->query("SELECT ct.*,(SELECT COUNT(*) FROM rental_charges rc WHERE rc.charge_type_id=ct.id) AS usage_count FROM rental_charge_types ct ORDER BY ct.is_active DESC,ct.sort_order,ct.name")->fetchAll();include __DIR__ . '/_header.php';
?>
<div class="admin-grid"><section class="panel"><div class="panel-head"><div><h2>Rental Charge Types</h2><p class="muted">Optional post-rental or recurring charges. Electricity and Water are built into the billing workflow; additional active types can be recorded manually.</p></div><a class="btn btn-outline btn-sm" href="rentables.php">Manage Rentables</a></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Charge Type</th><th>Code</th><th>Status</th><th>History</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><strong><?= e($row['name']) ?></strong></td><td><?= e($row['code']) ?></td><td><?= $row['is_active']?'Active':'Inactive' ?></td><td><?= (int)$row['usage_count'] ?></td><td><div class="admin-actions"><a class="btn btn-outline btn-sm" href="?edit=<?= (int)$row['id'] ?>">Edit</a><?php if((int)$row['usage_count']===0&&!in_array($row['code'],['electricity','water','extension','adjustment'],true)):?><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><button class="btn btn-danger btn-sm">Delete</button></form><?php endif;?></div></td></tr><?php endforeach;?></tbody></table></div></section><aside class="panel"><h2><?= $edit?'Edit Charge Type':'Add Charge Type' ?></h2><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><div class="form-group admin-form-gap"><label>Name *</label><input name="name" maxlength="120" value="<?= e($edit['name']??'') ?>" placeholder="Delivery" required></div><div class="form-group admin-form-gap"><label>Code</label><input name="code" maxlength="50" value="<?= e($edit['code']??'') ?>" placeholder="delivery"></div><label class="admin-check"><input type="checkbox" name="is_active" value="1"<?= !isset($edit['is_active'])||$edit['is_active']?' checked':'' ?>> Active</label><button class="btn btn-primary btn-block"><?= $edit?'Save Changes':'Add Charge Type' ?></button></form></aside></div>
<?php include __DIR__ . '/_footer.php'; ?>
