<?php
/**
 * FILE PURPOSE: Admin user/account management screen.
 * DEBUGGING: Treat passwords and active/disabled account state as security-sensitive; admin_required() revalidates active sessions.
 */
require_once __DIR__ . '/../includes/functions.php';admin_required();if(!is_admin()){flash('danger','Administrator access is required.');redirect('index.php');}$adminPageTitle='Users';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'create';
 try{
  if($action==='toggle'){$id=(int)$_POST['id'];if($id===current_admin()['id'])throw new RuntimeException('You cannot disable your own account.');$stmt=db()->prepare('UPDATE admins SET is_active=1-is_active WHERE id=?');$stmt->execute([$id]);flash('success','User status changed.');}
  elseif($action==='password'){$id=(int)$_POST['id'];$password=$_POST['password']??'';if(strlen($password)<8)throw new RuntimeException('Password must contain at least 8 characters.');$stmt=db()->prepare('UPDATE admins SET password_hash=? WHERE id=?');$stmt->execute([password_hash($password,PASSWORD_DEFAULT),$id]);flash('success','Password updated.');}
  else{$name=trim($_POST['full_name']??'');$username=trim($_POST['username']??'');$password=$_POST['password']??'';$role=$_POST['role']??'staff';if($name===''||$username===''||strlen($password)<8)throw new RuntimeException('Name, username, and a password of at least 8 characters are required.');if(!in_array($role,['admin','staff'],true))$role='staff';$stmt=db()->prepare('INSERT INTO admins(full_name,username,password_hash,role) VALUES(?,?,?,?)');$stmt->execute([$name,$username,password_hash($password,PASSWORD_DEFAULT),$role]);flash('success','User account created.');}
 }catch(Throwable $e){flash('danger',$e instanceof RuntimeException?$e->getMessage():'Unable to update the user account. The username may already exist.');}
 redirect('users.php');
}
try{$users=db()->query('SELECT * FROM admins ORDER BY full_name')->fetchAll();}catch(Throwable $e){$users=[];}
include __DIR__ . '/_header.php';
?>
<div class="admin-grid"><section class="panel"><div class="panel-head"><h2>Admin & Staff Accounts</h2></div><div class="table-wrap"><table class="admin-table mobile-card-table admin-users-table"><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Status</th><th>Reset Password</th><th></th></tr></thead><tbody><?php foreach($users as $user): ?><tr><td data-label="Name" data-priority="primary"><strong><?= e($user['full_name']) ?></strong></td><td data-label="Username"><?= e($user['username']) ?></td><td data-label="Role"><?= e(ucfirst($user['role'])) ?></td><td data-label="Status"><span class="status-pill status-<?= $user['is_active']?'success':'danger' ?>"><?= $user['is_active']?'Active':'Disabled' ?></span></td><td data-label="Reset Password"><form method="post" class="admin-actions admin-user-reset-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="password"><input type="hidden" name="id" value="<?= (int)$user['id'] ?>"><input type="password" name="password" placeholder="New password" minlength="8" required style="max-width:180px"><button class="btn btn-outline btn-sm">Reset</button></form></td><td data-label="Account Actions"><?php if((int)$user['id']!==current_admin()['id']): ?><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?= (int)$user['id'] ?>"><button class="btn <?= $user['is_active']?'btn-danger':'btn-primary' ?> btn-sm"><?= $user['is_active']?'Disable':'Enable' ?></button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></section><aside class="panel"><h2>Create User</h2><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="create"><div class="form-group" style="margin-bottom:12px"><label>Full Name</label><input name="full_name" required></div><div class="form-group" style="margin-bottom:12px"><label>Username</label><input name="username" required></div><div class="form-group" style="margin-bottom:12px"><label>Password</label><input type="password" name="password" minlength="8" required></div><div class="form-group" style="margin-bottom:18px"><label>Role</label><select name="role"><option value="staff">Staff</option><option value="admin">Administrator</option></select></div><button class="btn btn-primary btn-block">Create Account</button></form></aside></div>
<?php include __DIR__ . '/_footer.php'; ?>
